# Generated by Django 6.0.3 on 2026-06-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyjwt_user', '0002_remove_user_jwt_secret'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_email_type_unique',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email already exists.'}, help_text='Please Enter valid Email Address', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
